apiVersion: v1
kind: Service
metadata:
  name: festival-service-svc
  labels:
    app: festival-service
  namespace: festival-service
spec:
  selector:
    app: festival-service
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 5006
  type: ClusterIP