services:
  notice_service:
    build: ./notice_service
    ports:
      - "5004:5004"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: notice_db
      DB_USER: root
      DB_PASSWORD: mysql

  login_service:
    build: ./login_service
    ports:
      - "5006:5006"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: user_db
      DB_USER: root
      DB_PASSWORD: mysql

  main_service:
    build: ./main_service
    ports:
      - "5003:5003"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
