version: '3.8'

services:
  login_service:
    build:
      context: ./login_service
      dockerfile: Dockerfile.
    ports:
      - "5006:5006"
    expose:
      - "5006"
    depends_on:
      - mysql
    env_file:
      - ./login_service/.env
    networks:
      - app_network

  course_service:
    build:
      context: ./course_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    expose:
      - "5001"
    depends_on:
      - mysql
    env_file:
      - ./course_service/.env
    networks:
      - app_network

  festival_service:
    build:
      context: ./festival_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    expose:
      - "5002"
    depends_on:
      - mysql
    env_file:
      - ./festival_service/.env
    networks:
      - app_network

  main_service:
    build:
      context: ./main_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    expose:
      - "5003"
    depends_on:
      - mysql
    env_file:
      - ./main_service/.env
    networks:
      - app_network

  notice_service:
    build:
      context: ./notice_service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    expose:
      - "5004"
    depends_on:
      - mysql
    env_file:
      - ./notice_service/.env
    networks:
      - app_network

  mysql:
    image: kyk000306/test-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: P*ssW0rd
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
