version: "3.8"

services:
  login_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USER=root
      - DB_PASSWORD=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=user_db
    depends_on:
      - mysql
    ports:
      - "5006:5006"
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: