apiVersion: v1
kind: Service
metadata:
  name: login-service-svc
  labels:
    app: login-service
  namespace: login-service
spec:
  selector:
    app: login-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5006
  type: ClusterIP
