apiVersion: v1
kind: Service
metadata:
  name: course-service-svc
  labels:
    app: course-service
  namespace: course-service
spec:
  selector:
    app: course-service
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 5006
  type: ClusterIP