apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: course-service-applicationset
  namespace: course-service
spec:
  generators:
    - list:
        elements:
          - name: course-service-appset
            repoURL: 'git@github.com:YeongKyuKang/SchoolService.git'
            targetRevision: CourseService
            path: 'k8s'
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: course-service
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
